%%{init: {'theme':'neutral'}}%%

sequenceDiagram
    actor Cliente

    box Broker para API REST
    participant Orquestrador
    participant Configurações
    participant Ranqueador
    participant Monitoramento
    participant Mapeador
    participant Requisitor
    participant Validador
    participant Provedor
    end
    
    autonumber
    Cliente->>Orquestrador: Enviar request para o provedor
    Orquestrador->>Configurações: Identificar recurso que o cliente quer acessar
    Configurações->>Orquestrador: Configurações do recurso
    Orquestrador ->> Orquestrador: Tentar provedores