%%{init: {'theme': 'neutral'}}%%

sequenceDiagram
    participant Healthchecker
    participant Configurações
    participant Requisitor
    participant Provedor
    participant Monitorador

    autonumber
    Healthchecker->>Configurações: Obtém configurações do provedor
    Configurações->> Healthchecker: Configurações
    Healthchecker->>Requisitor: Enviar requisição
    Requisitor->>Provedor: Requisição
    Provedor->>Requisitor: Resposta
    Healthchecker->>Monitorador: Registra métricas da resposta
    Healthchecker-->>Healthchecker: Agendar próxima execução do health check