%%{init: {'theme': 'neutral'}}%%

sequenceDiagram
    actor Cliente
    participant Inicializador
    participant Configuracoes
    participant Monitorador

    autonumber
    Cliente->> Monitorador: Inicializa aplicação de monitoramento
    Cliente->>Inicializador: "Preenche" arquivo de configuração
    Cliente->>Inicializador: Inicializa o Broker
    Inicializador->>Configuracoes: Obtém configurações do cliente
    Configuracoes->>Inicializador: Configurações
    Inicializador->>Inicializador: Valida configurações
    alt Configurações inválidas
        Inicializador->>Cliente: Erro
    else Configurações válidas
        loop Para cada provedor configurado
            Inicializador->>Inicializador: Dispara health check para cada o provedor
        end
    end